# Generated by Django 3.1.2 on 2020-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
