# Generated by Django 3.1.2 on 2020-10-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_batches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batches',
            new_name='Batch',
        ),
    ]
