# Generated by Django 3.1.2 on 2020-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201007_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qtty', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-date']},
        ),
    ]
