# Generated by Django 3.1.2 on 2020-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cookie_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='qtty',
            field=models.FloatField(max_length=100),
        ),
    ]
